services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      # - "8883:8883"
      # - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  # zigbee2mqtt:
  #   image: koenkk/zigbee2mqtt
  #   container_name: zigbee2mqtt
  #   depends_on:
  #     - mosquitto
  #   volumes:
  #     - ./zigbee2mqtt/data:/app/data
  #   devices:
  #   - COM6:/dev/ttyUSB0
  #   restart: unless-stopped
  #   environment:
  #     - TZ=Europe/Stockholm